"""make item_id nullable in sales and related tables

Revision ID: 09a099d0f587
Revises: 
Create Date: 2026-03-28 18:28:44.002000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a099d0f587'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billitems', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('billitems_item_id_fkey'), 'billitems', type_='foreignkey')
    op.create_foreign_key(None, 'billitems', 'items', ['item_id'], ['item_id'], ondelete='SET NULL')
    op.alter_column('sales', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('sales_item_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'items', ['item_id'], ['item_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_item_id_fkey'), 'sales', 'items', ['item_id'], ['item_id'])
    op.alter_column('sales', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'billitems', type_='foreignkey')
    op.create_foreign_key(op.f('billitems_item_id_fkey'), 'billitems', 'items', ['item_id'], ['item_id'])
    op.alter_column('billitems', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
