"""cascading delete on sale adn other tables related item delted

Revision ID: d46d5852b3aa
Revises: 09a099d0f587
Create Date: 2026-03-28 19:11:37.061974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46d5852b3aa'
down_revision: Union[str, Sequence[str], None] = '09a099d0f587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
